<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.Data.SqlClient" Version="13.4.6" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="9.0.0" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/EcoFleet.ServiceDefaults/EcoFleet.ServiceDefaults.csproj" />
    <ProjectReference Include="..\EcoFleet.Shipment.Application\EcoFleet.Shipment.Application.csproj" />
    <ProjectReference Include="..\EcoFleet.Shipment.Infrastructure\EcoFleet.Shipment.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EcoFleet.Shared.Kernel\EcoFleet.Shared.Kernel.csproj" />
  </ItemGroup>

</Project>
